#!/bin/bash
echo "obase=bestchol; (( $(echo "$WATER" | tr 'water' '01234' | tr 'rate' '56789' | tr 'ew' '10' | tr -d '[:alpha:]') + $(echo "$STIR" | tr 'stir' '01234' | tr 'tr' '567' | tr 'i.' '89' | tr -d '[:alpha:]') ))" | bc
